### ISSUE TITLE
Consulting making an expression pack

### ISSUE THREAD

**Issue by 6boris** [MariaLetta/free-gophers-pack#2]
Hello, I am a gopher from China. I want to make your image into an emoticon package for free to WeChat and QQ users. What do you think?

https://sticker.weixin.qq.com

**Comment by MariaLetta** [comment]
Hi, nice to meet you 💗
China is cool! Of course you can use pictures to create free sticker packs.

**Comment by 6boris** [comment]
> Hi, nice to meet you 💗
> China is cool! Of course you can use pictures to create free sticker packs.

I still have one thing to ask, you have designed a very good picture, but it seems that you have not defined the  official title eq[Happy, sad,], can you define the theme for this cute little expression?

**Comment by MariaLetta** [comment]
It's up to you! You can take a look at Telegram stickers for reference, but it's not like requirement or something, it's very approximate, so feel free to choose any emotion you feel relevant. At the end they are Free Gophers.
