### ISSUE TITLE
Flames are missing!

### ISSUE THREAD

**Issue by steebchen** [MariaLetta/free-gophers-pack#4]
In Telegram, the flames in the "this is fine" sticker are missing:

![Selection_009](https://user-images.githubusercontent.com/5013932/57166606-046d4680-6dfb-11e9-9f0c-3579f3d0d90a.jpg)

**Comment by steebchen** [comment]
My reaction to this issue:

![Selection_010](https://user-images.githubusercontent.com/5013932/57166619-0f27db80-6dfb-11e9-9f38-96a237e01031.jpg)

**Comment by Maikuolan** [comment]
(Just a drive-by reply; Neither seeking nor providing support).

I didn't know there were Telegram stickers available for the free gophers pack.. that's pretty cool. I regularly use Telegram.. I might need to take a look at that, I think.

**Comment by MariaLetta** [comment]
Hi @steebchen thank you for your question. This was done intentionally. It's a kind of mini-version, which may be suitable for many different cases.

**Comment by steebchen** [comment]
Oh :( Any chance a new sticker with the flames could be included in the stickers pack?

**Comment by MariaLetta** [comment]
I'm not sure... Does anyone else want flames? :-)

**Comment by robojones** [comment]
How is it fine if there are no flames?
I want flames!!! :fire: :fire: :fire: :rofl:

**Comment by MariaLetta** [comment]
Hi guys!
Flames added! 🔥 Plus there are a couple of new stickers 🎉
Enjoy.

**Comment by steebchen** [comment]
Thanks so much!
