### ISSUE TITLE
Some pics pixel size are too large, can't import to Google Slides

### ISSUE THREAD

**Issue by mosdeo** [MariaLetta/free-gophers-pack#7]
![image](https://user-images.githubusercontent.com/6894543/74131883-55c72380-4c20-11ea-95ed-de57f51b9c52.png)

As fig, the "No"pic pixel size is 5000x5001，more than 25 million so can't import to Google Slides.
Another, "Yes"pic pixel size is 5000x5000，just right fitted to limit of Google Slides, I can directly import it to Google Slides.

But "No"pic have many side blank, so I think change the pixel size a little, will keep original quality.

**Comment by MariaLetta** [comment]
Thanks for the comment @mosdeo , I will check all the pictures for size. This is usually a technical problem with automatic import from the editor(

**Comment by mosdeo** [comment]
> Thanks for the comment @mosdeo , I will check all the pictures for size. This is usually a technical problem with automatic import from the editor(

31.png have same problem😟
